POST http://localhost:3000/categories
content-type: application/json

{
    "name": "Drama",
    "description": "Filmes de acao"
}

###

PUT http://localhost:3000/categories/0ac12349-8166-41b5-923b-4e54deb48d6c
content-type: application/json

{
    "name": "Drama",
    "description": "Filmes Dramaticos"
}

###
DELETE http://localhost:3000/categories/396852ce-8a81-44e5-ac8b-fa21c7b99347

###
GET http://localhost:3000/categories


###
GET http://localhost:3000/categories